[package]
name = "shipper-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "shipper"
path = "src/main.rs"

[dependencies]
shipper = { path = "../shipper" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
humantime = "2"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
assert_cmd = "2"
insta = "1"
predicates = "3"
serial_test = "3"
tempfile = "3"
tiny_http = "0.12"
